# Generated by Django 2.1.5 on 2020-02-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expert', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gunjan',
        ),
        migrations.AddField(
            model_name='expert',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
