# Generated by Django 3.0.4 on 2020-03-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expert', '0003_auto_20200202_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expert',
            old_name='File',
            new_name='File_Verify',
        ),
        migrations.AlterField(
            model_name='expert',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
