# Generated by Django 2.1.5 on 2020-02-02 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Expert', '0003_auto_20200202_2110'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Query_Reply', models.TextField(default='')),
                ('Expert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Expert.Expert')),
                ('Query_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Query')),
            ],
        ),
    ]
