# Generated by Django 2.1.5 on 2020-01-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200103_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Grains', 'Grains'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Other', 'Other')], default='Grains', max_length=15),
        ),
    ]
