# Generated by Django 2.1.5 on 2020-01-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200123_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.CharField(default='', max_length=123),
        ),
        migrations.AddField(
            model_name='post',
            name='net_profit',
            field=models.CharField(default='', max_length=123),
        ),
    ]
