# Generated by Django 2.1.5 on 2020-02-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expert', '0002_auto_20200202_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
