# Generated by Django 3.0.4 on 2020-03-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_query_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
    ]
